name: Storybook
on:
  push:
    branches:
      - master # if any push happens on branch `main`, run this workflow. You could also add `paths` to detect changes in specific folder

jobs:
  build:
    name: Build live examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build addon
        run: npm run build
      - name: Build examples
        run: npm run build:example
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./packages/examples/storybook-static

      - name: Install and Build
        run: |
          npm ci
          npm install -D @storybook/addon-designs
          npm run build-storybook

      - name: Deploy
        uses: actions/deploy-pages@v2
        with:
          branch: gh-pages
          folder: storybook-static # output folder from `npm run build-storybook`
